
name: 🐛 Normal Bug Report For Uni App
description: Report a normal bug such as Webf Usage/Build Error/Performance.
labels: bug

body:
  - type: textarea
    validations:
      required: true
    attributes:
      label: Related Uni App Components
      description: |
        Please provide the related uni-app components 
      placeholder: |
        uni-app components
  - type: textarea
    validations:
      required: true
    attributes:
      label: Code example
      description: |
        Please provide a minimal code example that reproduces the problem.
        You can use a repostory on Github or [Github Gist](https://gist.github.com) link.
      placeholder: |
        https://gist.github.com/xxx/xxx
        or
        ```
        const div = document.createElement('div')
        ```

  - type: textarea
    validations:
      required: true
    attributes:
      label: Expected results
      description: What did you want to see?
      placeholder: Please paste a picture or describe what did you want to see?

  - type: textarea
    validations:
      required: true
    attributes:
      label: Actual results
      description: What did you see?
      placeholder: What did you see?
